baseURL = 'http://formulaspy.com/'
languageCode = 'en-us'
title = 'FormulaSpy'
theme = "ananke"

[params]
  text_color = ""
  author = ""
  favicon = ""
  site_logo = "/images/formulaspy_logo_dark.png"
